Run auto checkin for lint issues

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,4 +1,4 @@
-name: Lint Python Code
+name: Lint and Fix Python Code
 
 on:
   push:
@@ -19,36 +19,51 @@ jobs:
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
-          python-version: '3.12'  # Use the Python version you need
+          python-version: '3.x'  # Use the version of Python you need
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8  # Install Flake8 or any other linter you prefer
+          pip install flake8 autopep8  # Install Flake8 and autopep8
+
+      - name: Read .flake8 configuration
+        run: |
+          if [ -f .flake8 ]; then
+            echo "Contents of .flake8:"
+            cat .flake8
+          else
+            echo ".flake8 file not found."
+          fi
 
       - name: Run flake8
         id: lint
         run: |
-          flake8 . --max-line-length=88 --extend-ignore=E203,W503 > lint_report.txt || true
+          flake8 . --max-line-length=500 --extend-ignore=E203,W503 > lint_report.txt || true
           echo "::set-output name=lint_report::$(cat lint_report.txt)"
       
+      - name: Auto-fix code
+        run: |
+          autopep8 --in-place --aggressive --aggressive .
+          flake8 . --max-line-length=500 --extend-ignore=E203,W503 > lint_report_after.txt || true
+          echo "::set-output name=lint_report_after::$(cat lint_report_after.txt)"
+
       - name: Check for linting issues
         run: |
-          if [[ -s lint_report.txt ]]; then
-            echo "Linting issues found:"
-            cat lint_report.txt
+          if [[ -s lint_report_after.txt ]]; then
+            echo "Linting issues found after auto-fix:"
+            cat lint_report_after.txt
             exit 1
           else
-            echo "No linting issues found."
+            echo "No linting issues found after auto-fix."
           fi
 
       - name: Commit and push changes
-        if: success() && steps.lint.outputs.lint_report != ''
+        if: success() && steps.lint.outputs.lint_report_after != ''
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           git config --global user.name "GitHub Action"
           git config --global user.email "action@github.com"
           git add .  # Add the files that have been modified
-          git commit -m "Linting fixes"
+          git commit -m "Auto-fix linting issues"
           git push
